### ISSUE TITLE
can not compile---demo

### ISSUE THREAD

**Issue by tuesday88** [frankshearar/SipStack#1]
Self.CalleeMedia := TIdSDPMultimediaSession.Create(Self.Profile);
[erro] not enough actual parameters

**Comment by tuesday88** [comment]
Self.Stack := TIdSipStackInterface.Create(Self.Signaller, Self.Timer, Conf);
[error]:Incompatible types:'TIdSipUserAgentFactory'and 'TLdTimerQueue'

**Comment by frankshearar** [comment]
I'd be happy to merge in a fix. I don't have a Delphi environment more. The demo had only ever been some rough prototype sketch; I had not meant it to be a working test environment.
